---
- name: Install nginx
  hosts: host.name.ip
  become: true

  tasks:
  - name: Add my packages 
    yum:
      name: "{{ item }}" 
      state: present
    with_items: 
     - arping 
     - policycoreutils-python 
     - httpd 


