---
- name: Install some packages
  hosts: linux
  become: true

  tasks:
  - name: Add my packages 
    package:
      name: "{{ item }}" 
      state: present
    loop:
     - arping 
     - apache2


